const RAW='https://raw.githubusercontent.com/pabloperezpetit-coder/oura-web/main/assets/';
const imageFiles={'_MG_5037.jpg':'_MG_5037.jpg','_MG_5034.jpg':'_MG_5034.jpg','_MG_5045.jpg':'_MG_5045.jpg','_MG_5032.jpg':'_MG_5032.jpg','oura.jpg':'oura.jpg'};
document.querySelectorAll('img').forEach(img=>{const clean=img.getAttribute('src')?.split('?')[0]||'';const name=clean.split('/').pop();if(imageFiles[name]) img.src=RAW+imageFiles[name]+'?v=4';});

const audio=document.getElementById('audio'),seek=document.getElementById('seek'),status=document.getElementById('status');const format=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;audio.volume=.8;
const sync=()=>{const playing=!audio.paused;document.body.classList.toggle('playing',playing);document.getElementById('playIcon').textContent=playing?'Ⅱ':'▶';document.getElementById('playText').textContent=playing?'Pausar':'Reproducir';document.querySelectorAll('.play-trigger').forEach(b=>{b.setAttribute('aria-label',playing?'Pausar Hola':'Reproducir Hola');b.setAttribute('aria-pressed',String(playing))});document.querySelector('.nav-listen').innerHTML=playing?'Pausar <span>Ⅱ</span>':'Escuchar <span>▶</span>';document.querySelector('.round-icon').textContent=playing?'Ⅱ':'▶';status.textContent=playing?'Sonando ahora · Hola — OURA':'Una maqueta. El comienzo de algo.';};
document.querySelectorAll('.play-trigger').forEach(button=>button.addEventListener('click',async()=>{if(audio.paused){try{await audio.play()}catch{status.textContent='No pudimos reproducir el audio. Intentá de nuevo.';document.getElementById('musica').scrollIntoView({behavior:'smooth'})}}else audio.pause()}));audio.addEventListener('play',sync);audio.addEventListener('pause',sync);audio.addEventListener('ended',sync);audio.addEventListener('loadedmetadata',()=>{seek.max=audio.duration;document.getElementById('duration').textContent=format(audio.duration)});audio.addEventListener('timeupdate',()=>{seek.value=audio.currentTime;document.getElementById('current').textContent=format(audio.currentTime)});seek.addEventListener('input',()=>{if(Number.isFinite(audio.duration))audio.currentTime=Number(seek.value)});document.getElementById('volume').addEventListener('input',e=>{audio.volume=Number(e.target.value)});audio.addEventListener('error',()=>{status.textContent='No se pudo cargar la canción. Recargá la página para volver a intentar.'});for(let i=0;i<65;i++){const bar=document.createElement('i');bar.style.setProperty('--h',`${12+Math.abs(Math.sin(i*1.73)*Math.cos(i*.41))*88}%`);bar.style.setProperty('--d',`${-(i%9)*.11}s`);document.getElementById('wave').append(bar)}
const motionPreference=window.matchMedia('(prefers-reduced-motion: reduce)');
if(!motionPreference.matches && 'IntersectionObserver' in window){const targets=document.querySelectorAll('.section-heading,.song-story,.record,.band>div,.dates>.eyebrow,.dates>h2,.show,.photos-heading,.photo-grid figure,.merch-heading,.merch-card,.social-band');const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:0.08});targets.forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)});motionPreference.addEventListener('change',e=>{if(e.matches){targets.forEach(el=>el.classList.add('is-visible'));observer.disconnect()}});}
document.querySelectorAll('[data-shape]').forEach(button=>button.addEventListener('click',()=>{document.getElementById('sticker-preview').classList.toggle('square',button.dataset.shape==='square');document.querySelectorAll('[data-shape]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)))}));
const galleryImages=[...document.querySelectorAll('.photo-grid figure img')];const photoDialog=document.getElementById('photo-dialog');let photoIndex=0;
function showPhoto(index){photoIndex=(index+galleryImages.length)%galleryImages.length;const source=galleryImages[photoIndex];const image=document.getElementById('large-photo');image.src=source.src;image.alt=source.alt;document.getElementById('photo-caption').textContent=source.closest('figure').querySelector('figcaption').textContent;document.getElementById('photo-counter').textContent=`${photoIndex+1} / ${galleryImages.length}`;}
galleryImages.forEach((image,index)=>{const button=document.createElement('button');button.className='gallery-open';button.setAttribute('aria-label','Agrandir : '+image.alt);image.replaceWith(button);button.append(image);button.addEventListener('click',()=>{showPhoto(index);photoDialog.showModal();document.body.classList.add('modal-open')})});
document.getElementById('photo-close').addEventListener('click',()=>photoDialog.close());photoDialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));photoDialog.addEventListener('click',e=>{if(e.target===photoDialog){const r=photoDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)photoDialog.close()}});document.getElementById('photo-prev').addEventListener('click',()=>showPhoto(photoIndex-1));document.getElementById('photo-next').addEventListener('click',()=>showPhoto(photoIndex+1));photoDialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();showPhoto(photoIndex+1)}if(e.key==='ArrowLeft'){e.preventDefault();showPhoto(photoIndex-1)}});
const mini=document.querySelector('.mini-player');let fullPlayerVisible=true,hasPlayed=false;
function updateMini(){mini.hidden=!hasPlayed||fullPlayerVisible;document.body.classList.toggle('has-mini',!mini.hidden);document.getElementById('mini-toggle').textContent=audio.paused?'Play':'Pausar';}
if('IntersectionObserver' in window)new IntersectionObserver(entries=>{fullPlayerVisible=entries[0].isIntersecting;updateMini()},{threshold:0}).observe(document.querySelector('.record'));
audio.addEventListener('play',()=>{hasPlayed=true;updateMini()});audio.addEventListener('pause',updateMini);audio.addEventListener('ended',()=>{hasPlayed=false;updateMini()});audio.addEventListener('timeupdate',()=>{document.getElementById('mini-time').textContent=format(audio.currentTime)});